Always skip Node.js tests on Node.js v24
`mozlog` uses `intel` which uses the builtin `utils.isError`
That function was removed in v24
For now we skip those tests on newer Node.

See https://nodejs.org/api/deprecations.html#DEP0048

The error:

    /tmp/pytest-of-circleci/pytest-0/test_logging_events_ping_with_0/node_modules/intel/lib/record.js:56
        if (a && ((isErr = util.isError(a)) || a instanceof Trace)) {
                                ^

    TypeError: util.isError is not a function